steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud compute ssh fdavirxxxxavier@my-projects --project=mydiscordbots-355614 --zone=us-west1-b -- 'cd mydomainhomepage && git pull && sudo cp -a ./. /var/www/html'

options:
  logging: CLOUD_LOGGING_ONLY
